/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module dff(d, clk, q);
  input clk;
  input d;
  output q;
  reg q = 1'h0;
  always @(posedge clk)
      q <= d;
endmodule

module iiitb_sipo(d, clk, q);
  input clk;
  input d;
  output [3:0] q;
  dff aa (
    .clk(clk),
    .d(d),
    .q(q[3])
  );
  dff bb (
    .clk(clk),
    .d(q[3]),
    .q(q[2])
  );
  dff cc (
    .clk(clk),
    .d(q[2]),
    .q(q[1])
  );
  dff dd (
    .clk(clk),
    .d(q[1]),
    .q(q[0])
  );
endmodule
